export const productsData = [
    {
        id : 1,
        title:"Grey Tie",
        quantity :3,
        descreption:"lorem inpsum",
        availableSizes:["M" , "L" , "XXL"],
        price : 10,
        isFreeShipping: true,
    },
    {
        id : 2,
        title:"Black Socks",
        quantity :2,
        descreption:"lorem inpsum",
        availableSizes:["M" , "L" , "XXL"],
        price : 20,
        isFreeShipping: true,
    },
    {
        id : 3,
        title:"Blue Jeans",
        quantity :6,
        descreption:"lorem inpsum",
        availableSizes:["S" , "XS" ],
        price : 26,
        isFreeShipping: true,
    },
    {
        id : 4,
        title:"Red Socks",
        quantity :2,
        descreption:"lorem inpsum",
        availableSizes:[ "L" , "M"],
        price : 32,
        isFreeShipping: false,
    },
    {
        id : 5,
        title:"Purple Shoes",
        quantity :3,
        descreption:"lorem inpsum",
        availableSizes:[ "L" , "M"],
        price : 36,
        isFreeShipping: false,
    },
    {
        id : 6,
        title:"Yello Shirt",
        quantity :2,
        descreption:"lorem inpsum",
        availableSizes:[ "L" , "M"],
        price : 39,
        isFreeShipping: false,
    },
] 