export const productsData = [
    {
        id : 1,
        title:"Grey Tie",
        quantity :3,
        descreption:"lorem inpsum",
        availableSizes:["X" , "L" , "XXL"],
        price : 10,
        isFreeShipping: true,
    },
    {
        id : 2,
        title:"Black ",
        quantity :2,
        descreption:"lorem inpsum",
        availableSizes:["X" , "L" , "XXL"],
        price : 20,
        isFreeShipping: true,
    },
    {
        id : 3,
        title:"Jeans",
        quantity :6,
        descreption:"lorem inpsum",
        availableSizes:["X" , "L" , "XXL"],
        price : 26,
        isFreeShipping: true,
    },
    {
        id : 4,
        title:"Socks",
        quantity :2,
        descreption:"lorem inpsum",
        availableSizes:["X" , "L" , "XXL"],
        price : 14,
        isFreeShipping: false,
    },
] 